apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: swim
  namespace: openshift-gitops
spec:
  description: SWIM reference architecture — GitOps delivery (OpenShift / Kubernetes)
  sourceRepos:
    - http://gitea-http.gitea.svc.cluster.local:3000/swimadmin/*
    - https://dl.gitea.com/charts/
  destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: swim-demo
      server: https://kubernetes.default.svc
    - namespace: swim-pipeline
      server: https://kubernetes.default.svc
    - namespace: openshift-operators
      server: https://kubernetes.default.svc
    - namespace: openshift-marketplace
      server: https://kubernetes.default.svc
    - namespace: gitea
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: operators.coreos.com
      kind: '*'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: cert-manager.io
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
