{{- if .Values.mongodb.enabled }}
{{- range .Values.mongodb.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    component: database
    {{- include "swim-ffice-infra.labels" $ | nindent 4 }}
type: Opaque
stringData:
  database-name: {{ .databaseName }}
  database-user: {{ $.Values.mongodb.credentials.user }}
  database-password: {{ $.Values.mongodb.credentials.password }}
  database-admin-password: {{ $.Values.mongodb.credentials.adminPassword }}
{{- end }}
{{- end }}
