kafka:
  enabled: true
  retention:
    ms: 604800000
    bytes: 268435456
  topics:
    - name: dnotam-inbox-topic
      partitions: 10
    - name: dnotam-events-all-topic
      partitions: 10
    - name: dnotam-events-closure-topic
      partitions: 3
    - name: dnotam-events-restriction-topic
      partitions: 3
    - name: dnotam-events-surface-condition-topic
      partitions: 3
    - name: dnotam-events-airspace-topic
      partitions: 3
    - name: dnotam-events-hazards-navaids-topic
      partitions: 3
    - name: dnotam-events-others-topic
      partitions: 3
    - name: dnotam-events-dlq-topic
      partitions: 1

mongodb:
  enabled: true
  image: "quay.io/mongodb/mongodb-community-server:8.0-ubi9-slim"
  storageSize: "1Gi"
  credentials:
    user: swim
    password: swim123
    adminPassword: admin123
  instances:
    - name: dnotam-consumer-mongodb
      databaseName: swim-dnotam

mariadb:
  enabled: true
  image: "docker.io/library/mariadb:12-ubi"
  storageSize: "1Gi"
  credentials:
    user: swim
    password: swim
    rootPassword: root
  instances:
    - name: dnotam-consumer-validator-mariadb
      databaseName: swim_consumer_validator
    - name: dnotam-provider-validator-mariadb
      databaseName: swim_provider_validator

postgres:
  enabled: true
  image: "registry.redhat.io/rhel9/postgresql-16:latest"
  storageSize: "1Gi"
  credentials:
    user: swim-provider
    password: swim-provider
  instances:
    - name: dnotam-provider-postgres
      databaseName: swim-dnotam
