{{- if .Values.postgres.enabled }}
{{- range .Values.postgres.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    component: database
    {{- include "swim-ed254-infra.labels" $ | nindent 4 }}
type: Opaque
stringData:
  database-user: {{ $.Values.postgres.credentials.user }}
  database-password: {{ $.Values.postgres.credentials.password }}
{{- end }}
{{- end }}
