apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swim-dnotam-provider-validator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: swim
  sources:
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/swimadmin/swim-dnotam-provider-validator.git
      targetRevision: main
      path: src/main/helm/swim-dnotam-provider-validator
      helm:
        valueFiles:
          - $values/apps/dnotam/provider-validator/overlays/crc-local/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/swimadmin/swim-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: swim-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
