apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swim-workspace-pvc
  namespace: swim-pipeline
  labels:
    app.kubernetes.io/part-of: swim-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-pvc
  namespace: swim-pipeline
  labels:
    app.kubernetes.io/part-of: swim-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
