apiVersion: v2
name: swim-ffice-infra
description: SWIM FF-ICE service infrastructure — Kafka topics, MongoDB, MariaDB, PostgreSQL
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - swim
  - ffice
  - ff-ice
  - infrastructure
  - kafka
  - mongodb
  - mariadb
  - postgresql
maintainers:
  - name: SWIM Developer
