apiVersion: v2
name: swim-core-infra
description: SWIM core shared infrastructure — PKI, Kafka cluster (no topics), Keycloak
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - swim
  - infrastructure
  - kafka
  - keycloak
  - pki
maintainers:
  - name: SWIM Developer
