apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel9
  namespace: openshift-operators
spec:
  channel: 7.14.x
  name: amq-broker-rhel9
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
