apiVersion: v1
kind: Namespace
metadata:
  name: swim-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhbk-operator-group
  namespace: swim-demo
spec:
  targetNamespaces:
    - swim-demo
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: swim-demo
spec:
  channel: stable-v26.4
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
