apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swim-platform-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: swim
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/swimadmin/swim-gitops.git
    targetRevision: main
    path: platform/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
