apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swim-core-infra
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: swim
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/swimadmin/swim-gitops.git
    targetRevision: main
    path: infra/swim-core-infra/chart
    helm:
      releaseName: swim-core-infra
      valueFiles:
        - ../../overlays/crc-local/core-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: swim-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
