{{- if .Values.mariadb.enabled }}
{{- range .Values.mariadb.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    component: database
    {{- include "swim-ffice-infra.labels" $ | nindent 4 }}
type: Opaque
stringData:
  user: {{ $.Values.mariadb.credentials.user }}
  password: {{ $.Values.mariadb.credentials.password }}
  root-password: {{ $.Values.mariadb.credentials.rootPassword }}
{{- end }}
{{- end }}
