{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: kafka
    {{- include "swim-infra.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storageSize }}
        deleteClaim: true
{{- end }}
