{{- if .Values.mariadb.enabled }}
{{- range .Values.mariadb.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    component: database
    {{- include "swim-dnotam-infra.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .name }}
    component: database
{{- end }}
{{- end }}
